### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [kazzmir/x11-racket#4]
Am I missing a license deceleration somewhere? 

I want to make a TinyWM port to Racket, then build up from there -- and was wanting to use these bindings but don't want to commit to them without a formal deceleration somewhere.

**Comment by kazzmir** [comment]
It will be dual apache 2.0/MIT licensed. I will add the license files soon.

**Comment by ghost** [comment]
Great to hear; Thanks!

**Comment by ghost** [comment]
Thanks for this!
Time to play around. ;)
